---
- hosts: all
  become: yes
  roles:
    - update_upgrade

- hosts: webservers
  become: yes
  roles:
    - webservers

- hosts: workstations
  become: yes
  roles:
    - workstations
    - install_docker
