- name: Add Group
  group:
    name: devops
    state: present

- name: Create a list of users
  user:
    name: "{{item}}"
    state: present
    groups: root
    loop:
      - Bryan
      - User1
      - User2
      - User3