- name: Install Multiple Packages
  apt:
    name: 
      - htop
      - net-tools
      - unzip
    state: present
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

- name: Installing Terraform 
  unarchive:
    src: https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"